//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoPark.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoPark.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Car with this number already exists!.
        /// </summary>
        internal static string AddCarBadResponse {
            get {
                return ResourceManager.GetString("AddCarBadResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Car has been added!.
        /// </summary>
        internal static string AddCarResponse {
            get {
                return ResourceManager.GetString("AddCarResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Category with this name already exists!.
        /// </summary>
        internal static string AddCategoryBadResponse {
            get {
                return ResourceManager.GetString("AddCategoryBadResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Category has been added!.
        /// </summary>
        internal static string AddCategoryResponse {
            get {
                return ResourceManager.GetString("AddCategoryResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ..\..\Properties\DataSources\images\cars\.
        /// </summary>
        internal static string carsImagePath {
            get {
                return ResourceManager.GetString("carsImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ..\\..\\Properties\\DataSources\\DataBase\\defaultDataBase.xml.
        /// </summary>
        internal static string defaultPath {
            get {
                return ResourceManager.GetString("defaultPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attempt to delete category, if there are cars with with type!.
        /// </summary>
        internal static string DeleteCategoryWithCars {
            get {
                return ResourceManager.GetString("DeleteCategoryWithCars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Car with this number already exists!.
        /// </summary>
        internal static string EditCarBadResponce {
            get {
                return ResourceManager.GetString("EditCarBadResponce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Car has been updated!.
        /// </summary>
        internal static string EditCarResponse {
            get {
                return ResourceManager.GetString("EditCarResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ..\\..\\Properties\\DataSources\\DataBase\\dataBase.xml.
        /// </summary>
        internal static string filePath {
            get {
                return ResourceManager.GetString("filePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на c:\\.
        /// </summary>
        internal static string InitialDirectoryPath {
            get {
                return ResourceManager.GetString("InitialDirectoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number is invalid! Use only A-Z and 0-9.
        /// </summary>
        internal static string InvalidCarNumber {
            get {
                return ResourceManager.GetString("InvalidCarNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Category name is invalid!.
        /// </summary>
        internal static string InvalidCategoryName {
            get {
                return ResourceManager.GetString("InvalidCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data is invalid!.
        /// </summary>
        internal static string InvalidData {
            get {
                return ResourceManager.GetString("InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Model name is invalid!.
        /// </summary>
        internal static string InvalidModelName {
            get {
                return ResourceManager.GetString("InvalidModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type car isn&apos;t selected!.
        /// </summary>
        internal static string InvalidTypeCar {
            get {
                return ResourceManager.GetString("InvalidTypeCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Category isn&apos;t selected!.
        /// </summary>
        internal static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attempt to change cat type, if there are cars with with type!.
        /// </summary>
        internal static string UpdateCategoryBadCarType {
            get {
                return ResourceManager.GetString("UpdateCategoryBadCarType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Category with this name already exists!.
        /// </summary>
        internal static string UpdateCategoryBadResponse {
            get {
                return ResourceManager.GetString("UpdateCategoryBadResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Category has been updated!.
        /// </summary>
        internal static string UpdateCategoryResponse {
            get {
                return ResourceManager.GetString("UpdateCategoryResponse", resourceCulture);
            }
        }
    }
}
